name: Workflow kpawluk
on: [push]
jobs:
    example-actions:
      runs-on: macos-latest
         - name: Docker building image
           uses: actions/checkout@v2
           run: |
             docker --version
             python3 --version
             docker build --tag test-flask-app .
         - name: Testing by pylint
           uses: action/setup-python@v1
           with:
             python-version: 3.10
           run: |
             python -m pip install --upgrade pip
             pip install pylint
             pylint app.py
