name: Workflow kpawluk
on: [push]
jobs:
  workflow-actions:
    runs-on: macos-latest
    steps:
      - name: Docker and python version
        uses: actions/checkout@v2
        run: |
          docker --version
          python3 --version
      - name: Testing pylint
        uses: actions/setup-python@v1
        with:
          python-version: 3.10
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pylint app.py
      - name: Docker image
        run: docker build --tag test-flask-app .
