name: Workflow kpawluk
on: [push]
jobs:
     version-check:
       runs-on: macos-latest
       steps:
            - run: docker --version
            - run: python3 --version
     pylint-check:
       runs-on: macos-latest
       steps:
            - run: pylint app.py
     docker-check:
       runs-on: macos-latest
       steps:
            - run: docker build --tag test-flask-app .
